/** Must match apps/api/app/Constants/ErrorCodes.php */
export const ERROR_CODES = {
  INVALID_PHONE: 'INVALID_PHONE',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_RATE_LIMIT: 'OTP_RATE_LIMIT',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_NID: 'DUPLICATE_NID',
  DUPLICATE_PLATE: 'DUPLICATE_PLATE',
  NO_DRIVERS: 'NO_DRIVERS',
  OUT_OF_ZONE: 'OUT_OF_ZONE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  PIN_MISMATCH: 'PIN_MISMATCH',
  ALREADY_PAID: 'ALREADY_PAID',
  SOS_NOT_ALLOWED: 'SOS_NOT_ALLOWED',
  GUARDIAN_CAP: 'GUARDIAN_CAP',
  DUPLICATE_GUARDIAN: 'DUPLICATE_GUARDIAN',
  DEBT_CAP: 'DEBT_CAP',
  GRACE_OVER: 'GRACE_OVER',
  SMS_FAILED: 'SMS_FAILED',
  ALREADY_RATED: 'ALREADY_RATED',
  BLOCKED: 'BLOCKED',
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
