export const ERROR_CODES = {
  INVALID_PHONE: 'INVALID_PHONE',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_RATE_LIMIT: 'OTP_RATE_LIMIT',
  NO_DRIVERS: 'NO_DRIVERS',
  OUT_OF_ZONE: 'OUT_OF_ZONE',
  SOS_NOT_ALLOWED: 'SOS_NOT_ALLOWED',
  ALREADY_PAID: 'ALREADY_PAID',
  DEBT_CAP: 'DEBT_CAP',
  GRACE_OVER: 'GRACE_OVER',
} as const;
